sudo: required

services:
  - docker

before_install:
- gem install jekyll

script:
- ls
- jekyll build .

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$AWS_BUCKET"
  local_dir: "_site"
